### ISSUE TITLE
Game gives a crash log when creating path blocks with a shovel

### ISSUE THREAD

**Issue by Dakotaraptor** [MinecraftBoomMod/Minecraft-Boom#5] opened 2018-05-22 18:09 UTC
https://pastebin.com/hKycjbFi

It's definitely Minecraft Boom that causes this crash, I disabled mods one by one until I found the resulting mod. Happens with and without Dirt2Path installed, though it also prevents shift-right clicking with a shovel turning path into dirt (an interaction added by said mod)

**Comment by Soupbubbles** [comment] 2018-05-23 09:39
You will have to give me more information. When I have both Dirt2Path installed and Survival Mechanics I get no crash. The crahs says it's caused by Survival Mechanics:

Caused by: java.lang.NullPointerException
    at sorazodia.survival.mechanics.PlayerActionEvent.placeBlocks(PlayerActionEvent.java:189)
    at sorazodia.survival.mechanics.PlayerActionEvent.blockRightClick(PlayerActionEvent.java:156)

**Comment by Soupbubbles** [comment] 2018-05-23 10:06
I have now fixed the bug where it prevents shift + right-clicking with a shovel. But I never got a crash, what were you doing when the client crashed?

**Comment by Dakotaraptor** [comment] 2018-05-24 02:03
Sorry, it was a bug but not a crash, I'm not sure what to call it. I didn't get a client crash, but VanillaFix notified me there was an error

**Comment by Soupbubbles** [comment] 2018-05-24 12:03
Ah okay then! This will be fixed in the next update!

**Closed by Soupbubbles** 2018-05-24 12:03 UTC
